# Header
logo: Peter Hou's Logo

# navigatior items
navitems:
  Home: /
  CV: /CV.pdf
  Research: /research
  Honors: /honors
  Gallery: /gallery
  About: /about

stylesheets:
  - /css/style.css

scripts:
  - /js/scripts.js
  - /js/home.js
  - /js/nonhome.js

mainimage: /image/main/over-water-road.jpg

certificates:
	- /image/honors/scholarshipB.png
	- /image/honors/PRAXAIR.jpg
	- /image/honors/MSRA.jpg
	- /image/honors/NUEDC.jpg
	- /image/honors/League.png
	- /image/honors/jihanbing.jpg
	- /image/honors/cv_Page23.png
	- /image/honors/cv_Page22.png
	- /image/honors/cv_Page24.png
	- /image/honors/graduate.jpg
	- /image/honors/cv_Page21.png
	- /image/honors/cv_Page20.png
	- /image/honors/cv_Page19.png
	- /image/honors/cv_Page18.png
	- /image/honors/cv_Page17.png
	- /image/honors/cv_Page15.png
	- /image/honors/cv_Page14.png
	- /image/honors/cv_Page16.png
	- /image/honors/ctScholar.jpg
	- /image/honors/cv_Page13.png
	- /image/honors/BuildingBridges.jpg
	- /image/honors/chuntsung.jpg
	- /image/honors/mcm.png

post_asset_folder: true
