# Header
logo: Peter Hou's Logo

# navigatior items
navitems:
  Home: /
  CV: /CV.pdf
  Research: /research
  Honors: /honors
  Gallery: /gallery
  About: /about

stylesheets:
  - /css/style.css

scripts:
  - /js/scripts.js
  - /js/home.js
  - /js/nonhome.js

certificates:
	- https://s1.imagehub.cc/images/2022/06/21/scholarshipB.png
	- https://s1.imagehub.cc/images/2022/06/21/PRAXAIR.jpg
	- https://s1.imagehub.cc/images/2022/06/21/MSRA.jpg
	- https://s1.imagehub.cc/images/2022/06/21/NUEDC.jpg
	- https://s1.imagehub.cc/images/2022/06/21/League.png
	- https://s1.imagehub.cc/images/2022/06/21/jihanbing.jpg
	- https://s1.imagehub.cc/images/2022/06/21/cv_Page23.png
	- https://s1.imagehub.cc/images/2022/06/21/cv_Page22.png
	- https://s1.imagehub.cc/images/2022/06/21/cv_Page24.png
	- https://s1.imagehub.cc/images/2022/06/21/graduate.jpg
	- https://s1.imagehub.cc/images/2022/06/21/cv_Page21.png
	- https://s1.imagehub.cc/images/2022/06/21/cv_Page20.png
	- https://s1.imagehub.cc/images/2022/06/21/cv_Page19.jpg
	- https://s1.imagehub.cc/images/2022/06/21/cv_Page18.png
	- https://s1.imagehub.cc/images/2022/06/21/cv_Page17.png
	- https://s1.imagehub.cc/images/2022/06/21/cv_Page15.png
	- https://s1.imagehub.cc/images/2022/06/21/cv_Page14.png
	- https://s1.imagehub.cc/images/2022/06/21/cv_Page16.png
	- https://s1.imagehub.cc/images/2022/06/21/ctScholar.jpg
	- https://s1.imagehub.cc/images/2022/06/21/cv_Page13.png
	- https://s1.imagehub.cc/images/2022/06/21/BuildingBridges.jpg
	- https://s1.imagehub.cc/images/2022/06/21/chuntsung.jpg
	- https://s1.imagehub.cc/images/2022/06/21/cv_Page12.jpg